name: release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      with:
        fetch-depth: 0
        persist-credentials: false
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: release the crate
      run: |
        cargo publish --token ${{ secrets.CARGO_TOKEN }}
